import { TxVacunacionSubCutaneaControlEficienciaModel } from './tx-vacunacion-subcutanea-control-eficiencia.model';
import { TxVacunacionSubCutaneayVacunaModel } from './tx-vacunacion-subcutanea-vacuna.model';
import { TxVacunacionSubCutaneaMaquinaModel } from './tx-vacunacion-subcutanea-maquina.model';
import { TxVacunacionSubCutaneaIrregularidadModel } from './tx-vacunacion-subcutanea-irregularidad.model';
import { TxVacunacionSubCutaneaFotosModel } from './tx-vacunacion-subcutanea-fotos.model';
import { TxVacunacionSubCutaneaDetalleModel } from './tx-vacunacion-subcutanea-detalle.model';
import { TxVacunacionSubCutaneaResultadoModel } from './tx-vacunacion-subcutanea-resultado.model';
import { TxVacunacionSubCutaneaPromedioModel } from './tx-vacunacion-subcutanea-promedio.model';
import * as moment from 'moment';

export class TxVacunacionSubCutaneaModel {
    idVacunacionSubCutanea: number;
    codigoEmpresa: string;
    descripcionEmpresa: string;
    codigoPlanta: string;
    descripcionPlanta: string;
    unidad: string;
    fecRegistro: Date;
    fecHoraRegistro: Date;
    responsableInvetsa: string;
    responsableIncubadora: string;
    horaIngreso: string;
    horaSalida: string;
    flgHyLine: boolean;
    flgLohman: boolean;
    flgRoss: boolean;
    flgCobb: boolean;
    flgOtros: boolean;
    observacionOtros: string;
    flgLunes: boolean;
    flgMartes: boolean;
    flgMiercoles: boolean;
    flgJueves: boolean;
    flgViernes: boolean;
    flgSabado: boolean;
    flgDomingo: boolean;
    flgAntibiotico?: boolean;
    nombreAntibiotico: string;
    dosisAntibiotico: string;
    flgPorcentajeViabilidad?: boolean;
    puntajePorcentajeViabilidad?: number;
    observacionInvetsa: string;
    observacionPlanta: string;
    promedioPollos: number;
    responsablePlanta: string;
    firmaInvetsa: string;
    firmaPlanta: string;
    flgCerrado: boolean;
    idUsuarioCierre: number;
    fecCierre: Date;
    emailFrom: string;
    emailTo: string;
    nombreArchivo: string;
    usuarioCierre: string;
    usuarioCreacion: string;
    flgMigrado: boolean;
    listarTxVacunacionSubCutaneaDetalle: TxVacunacionSubCutaneaDetalleModel[];
    listarTxVacunacionSubCutaneaFotos: TxVacunacionSubCutaneaFotosModel[];
    listarTxVacunacionSubCutaneaIrregularidad: TxVacunacionSubCutaneaIrregularidadModel[];
    listarTxVacunacionSubCutaneaMaquina: TxVacunacionSubCutaneaMaquinaModel[];
    listarTxVacunacionSubCutaneaVacuna: TxVacunacionSubCutaneayVacunaModel[];
    listarTxVacunacionSubCutaneaControlEficiencia: TxVacunacionSubCutaneaControlEficienciaModel[];
    listarTxVacunacionSubCutaneaResultado: TxVacunacionSubCutaneaResultadoModel[];
    listarTxVacunacionSubCutaneaPromedio: TxVacunacionSubCutaneaPromedioModel[];

    // Auditoria
    regUsuario?: number;
    regEstacion?: string;

    constructor() {
        this.idVacunacionSubCutanea = 0;
        this.codigoEmpresa = '';
        this.descripcionEmpresa = '';
        this.codigoPlanta = '';
        this.descripcionPlanta = '';
        this.unidad = '';
        this.fecRegistro = null;
        this.fecHoraRegistro = null;
        this.responsableInvetsa = '';
        this.responsableIncubadora = '';
        this.horaIngreso = moment().format("HH:mm");
        this.horaSalida = null;
        this.flgHyLine = false;
        this.flgLohman = false;
        this.flgRoss = false;
        this.flgCobb = false;
        this.flgOtros = false;
        this.observacionOtros = '';
        this.flgLunes = false;
        this.flgMartes = false;
        this.flgMiercoles = false;
        this.flgJueves = false;
        this.flgViernes = false;
        this.flgSabado = false;
        this.flgDomingo = false;
        this.flgAntibiotico = false;
        this.nombreAntibiotico = '';
        this.dosisAntibiotico = '';
        this.flgPorcentajeViabilidad = false;
        this.puntajePorcentajeViabilidad = 0;
        this.observacionInvetsa = '';
        this.observacionPlanta = '';
        this.promedioPollos = 0;
        this.responsablePlanta = '';
        this.firmaInvetsa = '';
        this.firmaPlanta = '';
        this.flgCerrado = false;
        this.idUsuarioCierre = 0;
        this.fecCierre = null;
        this.emailFrom = '';
        this.emailTo = '';
        this.nombreArchivo = '';
        this.usuarioCierre = '';
        this.usuarioCreacion = '';
        this.flgMigrado = false;
        this.listarTxVacunacionSubCutaneaDetalle = [];
        this.listarTxVacunacionSubCutaneaFotos = [];
        this.listarTxVacunacionSubCutaneaIrregularidad = [];
        this.listarTxVacunacionSubCutaneaMaquina = [];
        this.listarTxVacunacionSubCutaneaVacuna = [];
        this.listarTxVacunacionSubCutaneaControlEficiencia = [];
        this.listarTxVacunacionSubCutaneaResultado = [];
        this.listarTxVacunacionSubCutaneaPromedio = [];
        this.regUsuario = 0;
        this.regEstacion = '';
    }
}